name: "build docker image"
on:
  schedule:
    - cron:  '0 23 * * *'

jobs:

  publish_docker_image:
    name: Publish docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Download build for x86_64-unknown-linux-gnu
        uses: actions/download-artifact@v1
        with:
          name: dhall-mock-server-x86_64-unknown-linux-gnu
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dhallmock/dhall-mock
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
