name: "build docker image"
on:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build x86_64-unknown-linux-gnu release binary
        uses: actions-rs/cargo@v1
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu --release --features vendored
      - name: Store x86_64-unknown-linux-gnu release binary
        uses: actions/upload-artifact@v1
        with:
          name: dhall-mock-server-x86_64-unknown-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/dhall_mock_server

  publish_docker_image:
    name: Publish docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Download build for x86_64-unknown-linux-gnu
        uses: actions/download-artifact@v1
        with:
          name: dhall-mock-server-x86_64-unknown-linux-gnu
          path: target/release/dhall_mock_server
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dhallmock/dhall-mock
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: dockerfile/slim/Dockerfile
